"""Vocabulary for the first job-matching profile.

The lists in this module are intentionally conservative. A technology by itself
is not a job family; it becomes SWE evidence only when the surrounding text
describes software development work. Likewise, generic customer support is not
IT helpdesk evidence without an IT task or title.
"""

SWE = "swe"
IT_SUPPORT = "it_helpdesk_support"

SWE_STRONG_PHRASES = (
    "software engineer",
    "software developer",
    "software development",
    "lập trình viên",
    "lap trinh vien",
    "phát triển phần mềm",
    "phat trien phan mem",
    "kỹ sư phần mềm",
    "ky su phan mem",
    "lập trình phần mềm",
    "lap trinh phan mem",
    "kỹ sư lập trình",
    "ky su lap trinh",
    "nhân viên lập trình",
    "nhan vien lap trinh",
    "nhân viên phát triển phần mềm",
    "nhan vien phat trien phan mem",
    "thực tập sinh phần mềm",
    "thuc tap sinh phan mem",
    "thực tập phần mềm",
    "thuc tap phan mem",
    "thực tập sinh phát triển phần mềm",
    "thuc tap sinh phat trien phan mem",
    "thực tập phát triển phần mềm",
    "thuc tap phat trien phan mem",
    "swe",
    "sde",
    "swe intern",
    "fresher swe",
    "intern swe",
    "swe fresher",
    "sde intern",
    "fresher sde",
    "intern sde",
    "sde fresher",
    "backend developer",
    "backend engineer",
    "backend dev",
    "back-end dev",
    "frontend developer",
    "frontend engineer",
    "frontend dev",
    "front-end dev",
    "full stack developer",
    "fullstack developer",
    "full-stack developer",
    "full stack engineer",
    "fullstack engineer",
    "full stack dev",
    "fullstack dev",
    "full-stack dev",
    "web developer",
    "web engineer",
    "web dev",
    "mobile developer",
    "mobile engineer",
    "mobile dev",
    "application developer",
    "application dev",
    "app dev",
    "software dev",
    "java developer",
    "java dev",
    "python developer",
    "python dev",
    ".net developer",
    ".net dev",
    "node.js developer",
    "node.js dev",
    "nodejs developer",
    "nodejs dev",
    "react developer",
    "react dev",
    "flutter developer",
    "flutter dev",
    "golang dev",
    "dev intern",
    "fresher dev",
    "intern dev",
    "dev fresher",
)

SWE_CONTEXT_PHRASES = (
    "backend",
    "back-end",
    "frontend",
    "front-end",
    "full stack",
    "fullstack",
    "full-stack",
    "software engineer",
    "software developer",
    "developer",
    "dev",
    "engineer",
    "swe",
    "sde",
    "lập trình",
    "lap trinh",
    "phần mềm",
    "phan mem",
    "phát triển phần mềm",
    "phat trien phan mem",
)

TECHNOLOGY_PHRASES = (
    "java",
    "spring",
    "spring boot",
    "node.js",
    "nodejs",
    "python",
    ".net",
    "c#",
    "c++",
    "typescript",
    "javascript",
    "react",
    "angular",
    "vue",
    "flutter",
    "kotlin",
    "swift",
)

IT_STRONG_PHRASES = (
    "it helpdesk",
    "it help desk",
    "helpdesk",
    "help desk",
    "it support",
    "desktop support",
    "service desk",
    "end user support",
    "end-user support",
    "hỗ trợ cntt",
    "ho tro cntt",
    "nhân viên it",
    "nhan vien it",
    "kỹ thuật pc",
    "ky thuat pc",
    "kỹ thuật viên pc",
    "ky thuat vien pc",
    "it technician",
    "kỹ thuật viên it",
    "ky thuat vien it",
    "hỗ trợ kỹ thuật it",
    "ho tro ky thuat it",
)

IT_CONTEXT_PHRASES = (
    "technical support",
    "technical service",
    "it intern",
    "it fresher",
    "fresher it",
    "tts it",
    "it tts",
    "thực tập sinh it",
    "thuc tap sinh it",
    "thực tập it",
    "thuc tap it",
    "thực tập sinh cntt",
    "thuc tap sinh cntt",
    "thực tập cntt",
    "thuc tap cntt",
    "tts cntt",
    "fresher cntt",
    "cntt fresher",
    "thực tập sinh công nghệ thông tin",
    "thuc tap sinh cong nghe thong tin",
    "thực tập công nghệ thông tin",
    "thuc tap cong nghe thong tin",
    "fresher công nghệ thông tin",
    "fresher cong nghe thong tin",
    "tts cong nghe thong tin",
    "tts công nghệ thông tin",
    "it staff",
    "it officer",
    "nhân viên cntt",
    "nhan vien cntt",
    "kỹ thuật cntt",
    "ky thuat cntt",
    "nhân viên công nghệ thông tin",
    "nhan vien cong nghe thong tin",
    "pc support",
    "desktop",
    "service desk",
    "helpdesk",
    "công nghệ thông tin",
    "cong nghe thong tin",
    "cntt",
)

ENTRY_PHRASES = (
    "intern",
    "internship",
    "fresher",
    "fresh graduate",
    "graduate",
    "new graduate",
    "recent graduate",
    "entry level",
    "entry-level",
    "thực tập",
    "thuc tap",
    "thực tập sinh",
    "thuc tap sinh",
    "tts",
    "mới ra trường",
    "moi ra truong",
    "sinh viên mới ra trường",
    "sinh vien moi ra truong",
    "mới tốt nghiệp",
    "moi tot nghiep",
    "sinh viên mới tốt nghiệp",
    "sinh vien moi tot nghiep",
    "không yêu cầu kinh nghiệm",
    "khong yeu cau kinh nghiem",
    "chưa có kinh nghiệm",
    "chua co kinh nghiem",
    "chấp nhận sinh viên mới ra trường",
    "chap nhan sinh vien moi ra truong",
    "chấp nhận mới ra trường",
    "chap nhan moi ra truong",
)

OUTSIDE_LOCATION_PHRASES = (
    "hn",
    "hà nội",
    "ha noi",
    "hanoi",
    "đà nẵng",
    "da nang",
    "danang",
    "hải phòng",
    "hai phong",
    "đồng nai",
    "dong nai",
    "bình dương",
    "binh duong",
    "long an",
    "bà rịa",
    "ba ria",
    "vũng tàu",
    "vung tau",
    "cần thơ",
    "can tho",
    "bắc ninh",
    "bac ninh",
    "quảng ninh",
    "quang ninh",
)

HCM_LOCATION_PHRASES = (
    "hcm",
    "hcmc",
    "tp hcm",
    "tp. hcm",
    "tphcm",
    "thành phố hồ chí minh",
    "thanh pho ho chi minh",
    "hồ chí minh",
    "ho chi minh",
    "hochiminh",
    "sài gòn",
    "sai gon",
    "saigon",
)

RECRUITMENT_PHRASES = (
    "tuyển",
    "tuyen",
    "tuyển dụng",
    "tuyen dung",
    "hiring",
    "recruit",
    "recruitment",
    "join our team",
    "apply",
    "ứng tuyển",
    "ung tuyen",
)

OBVIOUS_NON_JOB_PHRASES = (
    "khóa học",
    "khoa hoc",
    "course",
    "cv của tôi",
    "cv cua toi",
    "tìm việc",
    "tim viec",
    "đang tìm việc",
    "dang tim viec",
)

# Passed to the Facebook reader as a broad, bounded prefilter. The classifier
# remains authoritative; this list only prevents reading every unrelated card.
CANDIDATE_PHRASES = tuple(dict.fromkeys(
    SWE_STRONG_PHRASES
    + SWE_CONTEXT_PHRASES
    + TECHNOLOGY_PHRASES
    + IT_STRONG_PHRASES
    + IT_CONTEXT_PHRASES
    + ENTRY_PHRASES
))
